(define (problem emergency_d1_l55_p55_c55_g55)
(:domain emergency)
(:objects
	drone1 - drone
	drone1_arm1 - arm
	drone1_arm2 - arm
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	loc48 - location
	loc49 - location
	loc50 - location
	loc51 - location
	loc52 - location
	loc53 - location
	loc54 - location
	loc55 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	crate48 - crate
	crate49 - crate
	crate50 - crate
	crate51 - crate
	crate52 - crate
	crate53 - crate
	crate54 - crate
	crate55 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
	person48 - person
	person49 - person
	person50 - person
	person51 - person
	person52 - person
	person53 - person
	person54 - person
	person55 - person
)
(:init
	(at-drone drone1 depot)
	(arm-of drone1_arm1 drone1)
	(arm-of drone1_arm2 drone1)
	(free drone1_arm1)
	(free drone1_arm2)
	(at-crate crate1 depot)
	(at-crate crate2 depot)
	(at-crate crate3 depot)
	(at-crate crate4 depot)
	(at-crate crate5 depot)
	(at-crate crate6 depot)
	(at-crate crate7 depot)
	(at-crate crate8 depot)
	(at-crate crate9 depot)
	(at-crate crate10 depot)
	(at-crate crate11 depot)
	(at-crate crate12 depot)
	(at-crate crate13 depot)
	(at-crate crate14 depot)
	(at-crate crate15 depot)
	(at-crate crate16 depot)
	(at-crate crate17 depot)
	(at-crate crate18 depot)
	(at-crate crate19 depot)
	(at-crate crate20 depot)
	(at-crate crate21 depot)
	(at-crate crate22 depot)
	(at-crate crate23 depot)
	(at-crate crate24 depot)
	(at-crate crate25 depot)
	(at-crate crate26 depot)
	(at-crate crate27 depot)
	(at-crate crate28 depot)
	(at-crate crate29 depot)
	(at-crate crate30 depot)
	(at-crate crate31 depot)
	(at-crate crate32 depot)
	(at-crate crate33 depot)
	(at-crate crate34 depot)
	(at-crate crate35 depot)
	(at-crate crate36 depot)
	(at-crate crate37 depot)
	(at-crate crate38 depot)
	(at-crate crate39 depot)
	(at-crate crate40 depot)
	(at-crate crate41 depot)
	(at-crate crate42 depot)
	(at-crate crate43 depot)
	(at-crate crate44 depot)
	(at-crate crate45 depot)
	(at-crate crate46 depot)
	(at-crate crate47 depot)
	(at-crate crate48 depot)
	(at-crate crate49 depot)
	(at-crate crate50 depot)
	(at-crate crate51 depot)
	(at-crate crate52 depot)
	(at-crate crate53 depot)
	(at-crate crate54 depot)
	(at-crate crate55 depot)
	(crate-has crate1 food)
	(crate-has crate2 food)
	(crate-has crate3 food)
	(crate-has crate4 food)
	(crate-has crate5 food)
	(crate-has crate6 food)
	(crate-has crate7 food)
	(crate-has crate8 food)
	(crate-has crate9 food)
	(crate-has crate10 food)
	(crate-has crate11 food)
	(crate-has crate12 food)
	(crate-has crate13 food)
	(crate-has crate14 food)
	(crate-has crate15 food)
	(crate-has crate16 food)
	(crate-has crate17 food)
	(crate-has crate18 food)
	(crate-has crate19 food)
	(crate-has crate20 food)
	(crate-has crate21 food)
	(crate-has crate22 food)
	(crate-has crate23 food)
	(crate-has crate24 food)
	(crate-has crate25 food)
	(crate-has crate26 food)
	(crate-has crate27 food)
	(crate-has crate28 food)
	(crate-has crate29 food)
	(crate-has crate30 food)
	(crate-has crate31 food)
	(crate-has crate32 food)
	(crate-has crate33 food)
	(crate-has crate34 food)
	(crate-has crate35 food)
	(crate-has crate36 food)
	(crate-has crate37 food)
	(crate-has crate38 food)
	(crate-has crate39 medicine)
	(crate-has crate40 medicine)
	(crate-has crate41 medicine)
	(crate-has crate42 medicine)
	(crate-has crate43 medicine)
	(crate-has crate44 medicine)
	(crate-has crate45 medicine)
	(crate-has crate46 medicine)
	(crate-has crate47 medicine)
	(crate-has crate48 medicine)
	(crate-has crate49 medicine)
	(crate-has crate50 medicine)
	(crate-has crate51 medicine)
	(crate-has crate52 medicine)
	(crate-has crate53 medicine)
	(crate-has crate54 medicine)
	(crate-has crate55 medicine)
	(at-person person1 loc20)
	(at-person person2 loc8)
	(at-person person3 loc32)
	(at-person person4 loc20)
	(at-person person5 loc18)
	(at-person person6 loc35)
	(at-person person7 loc14)
	(at-person person8 loc44)
	(at-person person9 loc11)
	(at-person person10 loc30)
	(at-person person11 loc26)
	(at-person person12 loc11)
	(at-person person13 loc26)
	(at-person person14 loc22)
	(at-person person15 loc12)
	(at-person person16 loc47)
	(at-person person17 loc25)
	(at-person person18 loc44)
	(at-person person19 loc39)
	(at-person person20 loc11)
	(at-person person21 loc24)
	(at-person person22 loc51)
	(at-person person23 loc42)
	(at-person person24 loc38)
	(at-person person25 loc25)
	(at-person person26 loc6)
	(at-person person27 loc26)
	(at-person person28 loc25)
	(at-person person29 loc49)
	(at-person person30 loc30)
	(at-person person31 loc50)
	(at-person person32 loc10)
	(at-person person33 loc54)
	(at-person person34 loc6)
	(at-person person35 loc24)
	(at-person person36 loc47)
	(at-person person37 loc10)
	(at-person person38 loc43)
	(at-person person39 loc47)
	(at-person person40 loc33)
	(at-person person41 loc18)
	(at-person person42 loc17)
	(at-person person43 loc50)
	(at-person person44 loc34)
	(at-person person45 loc42)
	(at-person person46 loc13)
	(at-person person47 loc40)
	(at-person person48 loc12)
	(at-person person49 loc23)
	(at-person person50 loc38)
	(at-person person51 loc27)
	(at-person person52 loc30)
	(at-person person53 loc23)
	(at-person person54 loc21)
	(at-person person55 loc21)
)
(:goal (and
	(at-drone drone1 depot)
	(person-has person3 food)
	(person-has person3 medicine)
	(person-has person5 food)
	(person-has person6 food)
	(person-has person10 food)
	(person-has person11 food)
	(person-has person13 food)
	(person-has person14 food)
	(person-has person15 food)
	(person-has person16 food)
	(person-has person18 medicine)
	(person-has person19 food)
	(person-has person20 food)
	(person-has person21 food)
	(person-has person21 medicine)
	(person-has person22 food)
	(person-has person22 medicine)
	(person-has person23 food)
	(person-has person24 food)
	(person-has person25 food)
	(person-has person26 food)
	(person-has person27 food)
	(person-has person27 medicine)
	(person-has person28 food)
	(person-has person31 food)
	(person-has person31 medicine)
	(person-has person32 food)
	(person-has person32 medicine)
	(person-has person33 medicine)
	(person-has person34 food)
	(person-has person35 food)
	(person-has person36 food)
	(person-has person37 food)
	(person-has person38 food)
	(person-has person39 food)
	(person-has person39 medicine)
	(person-has person40 food)
	(person-has person40 medicine)
	(person-has person41 medicine)
	(person-has person42 medicine)
	(person-has person43 food)
	(person-has person43 medicine)
	(person-has person44 food)
	(person-has person45 food)
	(person-has person46 food)
	(person-has person46 medicine)
	(person-has person47 medicine)
	(person-has person48 food)
	(person-has person49 food)
	(person-has person51 food)
	(person-has person52 medicine)
	(person-has person53 food)
	(person-has person54 food)
	(person-has person55 food)
	(person-has person55 medicine)
))
)
