(define (problem emergency_d1_l47_p47_c47_g47)
(:domain emergency)
(:objects
	drone1 - drone
	drone1_arm1 - arm
	drone1_arm2 - arm
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	loc21 - location
	loc22 - location
	loc23 - location
	loc24 - location
	loc25 - location
	loc26 - location
	loc27 - location
	loc28 - location
	loc29 - location
	loc30 - location
	loc31 - location
	loc32 - location
	loc33 - location
	loc34 - location
	loc35 - location
	loc36 - location
	loc37 - location
	loc38 - location
	loc39 - location
	loc40 - location
	loc41 - location
	loc42 - location
	loc43 - location
	loc44 - location
	loc45 - location
	loc46 - location
	loc47 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	crate21 - crate
	crate22 - crate
	crate23 - crate
	crate24 - crate
	crate25 - crate
	crate26 - crate
	crate27 - crate
	crate28 - crate
	crate29 - crate
	crate30 - crate
	crate31 - crate
	crate32 - crate
	crate33 - crate
	crate34 - crate
	crate35 - crate
	crate36 - crate
	crate37 - crate
	crate38 - crate
	crate39 - crate
	crate40 - crate
	crate41 - crate
	crate42 - crate
	crate43 - crate
	crate44 - crate
	crate45 - crate
	crate46 - crate
	crate47 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
	person21 - person
	person22 - person
	person23 - person
	person24 - person
	person25 - person
	person26 - person
	person27 - person
	person28 - person
	person29 - person
	person30 - person
	person31 - person
	person32 - person
	person33 - person
	person34 - person
	person35 - person
	person36 - person
	person37 - person
	person38 - person
	person39 - person
	person40 - person
	person41 - person
	person42 - person
	person43 - person
	person44 - person
	person45 - person
	person46 - person
	person47 - person
)
(:init
	(at-drone drone1 depot)
	(arm-of drone1_arm1 drone1)
	(arm-of drone1_arm2 drone1)
	(free drone1_arm1)
	(free drone1_arm2)
	(at-crate crate1 depot)
	(at-crate crate2 depot)
	(at-crate crate3 depot)
	(at-crate crate4 depot)
	(at-crate crate5 depot)
	(at-crate crate6 depot)
	(at-crate crate7 depot)
	(at-crate crate8 depot)
	(at-crate crate9 depot)
	(at-crate crate10 depot)
	(at-crate crate11 depot)
	(at-crate crate12 depot)
	(at-crate crate13 depot)
	(at-crate crate14 depot)
	(at-crate crate15 depot)
	(at-crate crate16 depot)
	(at-crate crate17 depot)
	(at-crate crate18 depot)
	(at-crate crate19 depot)
	(at-crate crate20 depot)
	(at-crate crate21 depot)
	(at-crate crate22 depot)
	(at-crate crate23 depot)
	(at-crate crate24 depot)
	(at-crate crate25 depot)
	(at-crate crate26 depot)
	(at-crate crate27 depot)
	(at-crate crate28 depot)
	(at-crate crate29 depot)
	(at-crate crate30 depot)
	(at-crate crate31 depot)
	(at-crate crate32 depot)
	(at-crate crate33 depot)
	(at-crate crate34 depot)
	(at-crate crate35 depot)
	(at-crate crate36 depot)
	(at-crate crate37 depot)
	(at-crate crate38 depot)
	(at-crate crate39 depot)
	(at-crate crate40 depot)
	(at-crate crate41 depot)
	(at-crate crate42 depot)
	(at-crate crate43 depot)
	(at-crate crate44 depot)
	(at-crate crate45 depot)
	(at-crate crate46 depot)
	(at-crate crate47 depot)
	(crate-has crate1 food)
	(crate-has crate2 food)
	(crate-has crate3 food)
	(crate-has crate4 food)
	(crate-has crate5 food)
	(crate-has crate6 food)
	(crate-has crate7 food)
	(crate-has crate8 food)
	(crate-has crate9 food)
	(crate-has crate10 food)
	(crate-has crate11 food)
	(crate-has crate12 food)
	(crate-has crate13 food)
	(crate-has crate14 food)
	(crate-has crate15 food)
	(crate-has crate16 food)
	(crate-has crate17 food)
	(crate-has crate18 food)
	(crate-has crate19 food)
	(crate-has crate20 food)
	(crate-has crate21 food)
	(crate-has crate22 food)
	(crate-has crate23 food)
	(crate-has crate24 food)
	(crate-has crate25 food)
	(crate-has crate26 food)
	(crate-has crate27 food)
	(crate-has crate28 medicine)
	(crate-has crate29 medicine)
	(crate-has crate30 medicine)
	(crate-has crate31 medicine)
	(crate-has crate32 medicine)
	(crate-has crate33 medicine)
	(crate-has crate34 medicine)
	(crate-has crate35 medicine)
	(crate-has crate36 medicine)
	(crate-has crate37 medicine)
	(crate-has crate38 medicine)
	(crate-has crate39 medicine)
	(crate-has crate40 medicine)
	(crate-has crate41 medicine)
	(crate-has crate42 medicine)
	(crate-has crate43 medicine)
	(crate-has crate44 medicine)
	(crate-has crate45 medicine)
	(crate-has crate46 medicine)
	(crate-has crate47 medicine)
	(at-person person1 loc15)
	(at-person person2 loc37)
	(at-person person3 loc38)
	(at-person person4 loc6)
	(at-person person5 loc38)
	(at-person person6 loc20)
	(at-person person7 loc35)
	(at-person person8 loc27)
	(at-person person9 loc23)
	(at-person person10 loc11)
	(at-person person11 loc38)
	(at-person person12 loc37)
	(at-person person13 loc24)
	(at-person person14 loc25)
	(at-person person15 loc12)
	(at-person person16 loc7)
	(at-person person17 loc41)
	(at-person person18 loc33)
	(at-person person19 loc3)
	(at-person person20 loc20)
	(at-person person21 loc45)
	(at-person person22 loc10)
	(at-person person23 loc14)
	(at-person person24 loc3)
	(at-person person25 loc43)
	(at-person person26 loc43)
	(at-person person27 loc35)
	(at-person person28 loc10)
	(at-person person29 loc46)
	(at-person person30 loc46)
	(at-person person31 loc41)
	(at-person person32 loc7)
	(at-person person33 loc30)
	(at-person person34 loc18)
	(at-person person35 loc11)
	(at-person person36 loc7)
	(at-person person37 loc34)
	(at-person person38 loc32)
	(at-person person39 loc37)
	(at-person person40 loc17)
	(at-person person41 loc7)
	(at-person person42 loc39)
	(at-person person43 loc47)
	(at-person person44 loc20)
	(at-person person45 loc39)
	(at-person person46 loc42)
	(at-person person47 loc5)
)
(:goal (and
	(at-drone drone1 depot)
	(person-has person1 medicine)
	(person-has person2 food)
	(person-has person3 food)
	(person-has person3 medicine)
	(person-has person5 food)
	(person-has person5 medicine)
	(person-has person6 medicine)
	(person-has person7 medicine)
	(person-has person8 food)
	(person-has person8 medicine)
	(person-has person9 food)
	(person-has person10 food)
	(person-has person10 medicine)
	(person-has person11 food)
	(person-has person11 medicine)
	(person-has person12 food)
	(person-has person13 food)
	(person-has person13 medicine)
	(person-has person14 food)
	(person-has person14 medicine)
	(person-has person16 food)
	(person-has person18 food)
	(person-has person19 food)
	(person-has person19 medicine)
	(person-has person20 food)
	(person-has person21 food)
	(person-has person23 medicine)
	(person-has person24 medicine)
	(person-has person26 food)
	(person-has person29 medicine)
	(person-has person31 food)
	(person-has person33 food)
	(person-has person33 medicine)
	(person-has person34 medicine)
	(person-has person35 food)
	(person-has person37 food)
	(person-has person38 medicine)
	(person-has person39 food)
	(person-has person40 medicine)
	(person-has person41 food)
	(person-has person42 food)
	(person-has person43 food)
	(person-has person43 medicine)
	(person-has person44 food)
	(person-has person45 food)
	(person-has person46 food)
	(person-has person46 medicine)
))
)
