(define (problem emergency_d1_l20_p20_c20_g20)
(:domain emergency)
(:objects
	drone1 - drone
	drone1_arm1 - arm
	drone1_arm2 - arm
	depot - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	loc11 - location
	loc12 - location
	loc13 - location
	loc14 - location
	loc15 - location
	loc16 - location
	loc17 - location
	loc18 - location
	loc19 - location
	loc20 - location
	crate1 - crate
	crate2 - crate
	crate3 - crate
	crate4 - crate
	crate5 - crate
	crate6 - crate
	crate7 - crate
	crate8 - crate
	crate9 - crate
	crate10 - crate
	crate11 - crate
	crate12 - crate
	crate13 - crate
	crate14 - crate
	crate15 - crate
	crate16 - crate
	crate17 - crate
	crate18 - crate
	crate19 - crate
	crate20 - crate
	food - content
	medicine - content
	person1 - person
	person2 - person
	person3 - person
	person4 - person
	person5 - person
	person6 - person
	person7 - person
	person8 - person
	person9 - person
	person10 - person
	person11 - person
	person12 - person
	person13 - person
	person14 - person
	person15 - person
	person16 - person
	person17 - person
	person18 - person
	person19 - person
	person20 - person
)
(:init
	(at-drone drone1 depot)
	(arm-of drone1_arm1 drone1)
	(arm-of drone1_arm2 drone1)
	(free drone1_arm1)
	(free drone1_arm2)
	(at-crate crate1 depot)
	(at-crate crate2 depot)
	(at-crate crate3 depot)
	(at-crate crate4 depot)
	(at-crate crate5 depot)
	(at-crate crate6 depot)
	(at-crate crate7 depot)
	(at-crate crate8 depot)
	(at-crate crate9 depot)
	(at-crate crate10 depot)
	(at-crate crate11 depot)
	(at-crate crate12 depot)
	(at-crate crate13 depot)
	(at-crate crate14 depot)
	(at-crate crate15 depot)
	(at-crate crate16 depot)
	(at-crate crate17 depot)
	(at-crate crate18 depot)
	(at-crate crate19 depot)
	(at-crate crate20 depot)
	(crate-has crate1 food)
	(crate-has crate2 food)
	(crate-has crate3 food)
	(crate-has crate4 food)
	(crate-has crate5 food)
	(crate-has crate6 food)
	(crate-has crate7 food)
	(crate-has crate8 food)
	(crate-has crate9 food)
	(crate-has crate10 food)
	(crate-has crate11 food)
	(crate-has crate12 food)
	(crate-has crate13 food)
	(crate-has crate14 food)
	(crate-has crate15 food)
	(crate-has crate16 food)
	(crate-has crate17 medicine)
	(crate-has crate18 medicine)
	(crate-has crate19 medicine)
	(crate-has crate20 medicine)
	(at-person person1 loc7)
	(at-person person2 loc12)
	(at-person person3 loc13)
	(at-person person4 loc6)
	(at-person person5 loc20)
	(at-person person6 loc9)
	(at-person person7 loc9)
	(at-person person8 loc19)
	(at-person person9 loc18)
	(at-person person10 loc8)
	(at-person person11 loc13)
	(at-person person12 loc10)
	(at-person person13 loc4)
	(at-person person14 loc5)
	(at-person person15 loc3)
	(at-person person16 loc3)
	(at-person person17 loc1)
	(at-person person18 loc19)
	(at-person person19 loc4)
	(at-person person20 loc5)
)
(:goal (and
	(at-drone drone1 depot)
	(person-has person1 food)
	(person-has person1 medicine)
	(person-has person2 food)
	(person-has person2 medicine)
	(person-has person3 food)
	(person-has person4 food)
	(person-has person5 food)
	(person-has person6 food)
	(person-has person7 food)
	(person-has person8 food)
	(person-has person9 food)
	(person-has person9 medicine)
	(person-has person10 food)
	(person-has person12 food)
	(person-has person12 medicine)
	(person-has person13 food)
	(person-has person14 food)
	(person-has person15 food)
	(person-has person16 food)
	(person-has person20 food)
))
)
